deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/globaltamilschool
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R *.php $DEPLOYPATH