<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Mukta+Malar:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet">
<?php include "css.php";?>
</head>
<body>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v11.0" nonce="tnNgt6o9"></script>
<?php include "header.php";?>
<div class="title-component">
  <h1 class="mukta-malar-bold">அண்மைச் செய்திகள்<br>LATEST NEWS</h1>
</div>

<div class="clearfix"></div>
<div class="page-content">
<div class="container">

<div class="sel-program">
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid026bEEYxq1SywdaqwiWwmMGE8erg6CSGLk6XFSQygU2dHhCn1KWQ2HW1z469Z8TcEfl&show_text=false&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid026d5v4QfBES9QPNfYgXFzYaoEUaDb2b7mjvB1AUZxPpmMdZPsaKjYHXoYnvqK2b58l&show_text=false&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid021RzZferXiXjibssrw6hTGbvzWNapbNtM6PPAP8Te6xBQYb6XeaVe47GSjiZSQHtol&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid0JN1dKGL93poYVmGAWjrfz3fxsFZGE1wb47Nyupaeu3m9Vr7RVKB8gHJqZ5izXPG7l&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid0HdJxe2EG4B1MGk5mxSBVyZfxvFyQibWoC5UyFWEgHj4Jgs5UviC7pA34mcUec63Ll&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid0PBNUXgwdpPYaYkJQepMToRG95swAtxwp83n5mLdW7oqeywPHsuiR1AMj3oEDYHSMl&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid022EdEgxVCHpEysSfZEBZ4NiywL6xGSyKgfgzaaX7Zc7UiuUZrCGxHiVNaDwZ7asusl&show_text=false&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid02yBV9kF3gtDWX4trgajpsAs7ApJPgyty5uvTNMK4uUAaNsBBBZdXr65Z1PMgBhLbUl&show_text=false&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid02Pz7ULSi7Zs9PgZKZvEYN7oCHE5zMhGwG4Y5jg1pdyzQfifZDVs4zTqwMeVn1gt7bl&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid02dX1F7nMFvPhGom5mShhumdHEsPGpcceM4M8HxBUn5UneYndYtFwbwq7X4mQR8nLtl&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid02vu1nQQZ4meL3dtzQQxRNwqgotdm9pBeP81F28LnbVxuZ8q8sRZUT5U1yf6bDDtf3l&show_text=false&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid02nbHfRCn5tjjamSa9T55cWaVkkxnhuaokspCA8ANrtgQxKLKDjuUzND78WuJVTYH1l&show_text=false&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid0iq63UjMeHNH8RefwGr7EMGNtKSxEMAXPqm1eEH7dZqSE3vSe9qC8Kdz7NUeheR1sl&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid03333EM6zMFo1nExoY3kWWyWvXk7sW4GZeQPNvfcWHuhEXwViE1x1ePuoQyntYw94Fl&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid02DcukZXFh432q9LHRqPhggLiu8F56QNCdSHEY9tu836CgqTxrQ2HNtijAtRACpuZul&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid037BJSWyQXfffwHsx7cztmmiKLo6gG7xdjtM2w2PstShkCEfKk5DHdHFdwmfy7tMF9l&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid0eAFG87cZvjV8M4FXmEkY9uRycuP1mqMFvvcDEnssV4RKNS8Euy93mB74vriVEbfKl&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid037PyCvUxPMsqY7seMYyck3umMErLBZigByZnxnFGwCXWN48BBm9ZjpoXCowAZQxmfl&show_text=false&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid029vCjy5SmsshffA9dbicCx2jVHz4hPZm4NmY5sKZQRRBKrvjNJrzLiB4tq77CJE1Nl&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid0C8k8zqfg16kjMhDMhuwCuSAues857UHJxnP9AdjKDj7vroX8gFXJrPdQi2thankGl&show_text=false&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fglobaltamilschool%2Fposts%2Fpfbid02Rzy2W4ds5mgrM86d2Tg4Ybiss3CbrTAGBC2jHQZbTjTjQVP2jaY87xUgZNP1FCLXl&show_text=true&width=500" width="auto" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
<div class="col-md-6 fb-post" data-href="https://www.facebook.com/mediapatners/posts/1264765273990841" data-width="auto" data-show-text="true"><blockquote cite="https://www.facebook.com/mediapatners/posts/1264765273990841" class="fb-xfbml-parse-ignore">Posted by <a href="https://www.facebook.com/globaltamilschool/">Global Tamil School</a> on&nbsp;<a href="https://www.facebook.com/mediapatners/posts/1264765273990841">Sunday, December 12, 2021</a></blockquote></div>
<div class="col-md-6 fb-post" data-href="https://www.facebook.com/globaltamilschool/posts/454354746267787" data-width="auto" data-show-text="true"><blockquote cite="https://www.facebook.com/globaltamilschool/posts/454354746267787" class="fb-xfbml-parse-ignore">Posted by <a href="https://www.facebook.com/globaltamilschool/">Global Tamil School</a> on&nbsp;<a href="https://www.facebook.com/globaltamilschool/posts/454354746267787">Sunday, December 12, 2021</a></blockquote></div>
<div class="col-md-6 fb-post" data-href="https://www.facebook.com/globaltamilschool/posts/455230359513559" data-width="auto" data-show-text="true"><blockquote cite="https://www.facebook.com/globaltamilschool/posts/455230359513559" class="fb-xfbml-parse-ignore">Posted by <a href="https://www.facebook.com/globaltamilschool/">Global Tamil School</a> on&nbsp;<a href="https://www.facebook.com/globaltamilschool/posts/455230359513559">Sunday, December 12, 2021</a></blockquote></div>
<div class="col-md-6 fb-post" data-href="https://www.facebook.com/globaltamilschool/posts/436966644673264" data-width="auto" data-show-text="true"><blockquote cite="https://www.facebook.com/globaltamilschool/posts/436966644673264" class="fb-xfbml-parse-ignore">Posted by <a href="https://www.facebook.com/globaltamilschool/">Global Tamil School</a> on&nbsp;<a href="https://www.facebook.com/globaltamilschool/posts/436966644673264">Sunday, October 10, 2021</a></blockquote></div>
<div class="col-md-6 fb-post" data-href="https://www.facebook.com/globaltamilschool/posts/417018533334742" data-width="auto" data-show-text="true"><blockquote cite="https://www.facebook.com/globaltamilschool/posts/417018533334742" class="fb-xfbml-parse-ignore">Posted by <a href="https://www.facebook.com/globaltamilschool/">Global Tamil School</a> on&nbsp;<a href="https://www.facebook.com/globaltamilschool/posts/417018533334742">Sunday, October 10, 2021</a></blockquote></div>
<div class="col-md-6 fb-post" data-href="https://www.facebook.com/globaltamilschool/posts/388972239472705" data-width="auto" data-show-text="true"><blockquote cite="https://www.facebook.com/globaltamilschool/posts/388972239472705" class="fb-xfbml-parse-ignore">Posted by <a href="https://www.facebook.com/globaltamilschool/">Global Tamil School</a> on&nbsp;<a href="https://www.facebook.com/globaltamilschool/posts/388972239472705">Thursday, August 26, 2021</a></blockquote></div>
<div class="col-md-6 fb-post" data-href="https://www.facebook.com/globaltamilschool/posts/374645624238700" data-width="auto" data-show-text="true"><blockquote cite="https://www.facebook.com/globaltamilschool/posts/374645624238700" class="fb-xfbml-parse-ignore">Posted by <a href="https://www.facebook.com/globaltamilschool/">Global Tamil School</a> on&nbsp;<a href="https://www.facebook.com/globaltamilschool/posts/374645624238700">Thursday, August 5, 2021</a></blockquote></div>
<div class="col-md-6 fb-post" data-href="https://www.facebook.com/globaltamilschool/posts/370441997992396" data-width="auto" data-show-text="true"><blockquote cite="https://www.facebook.com/globaltamilschool/posts/370441997992396" class="fb-xfbml-parse-ignore">Posted by <a href="https://www.facebook.com/globaltamilschool/">Global Tamil School</a> on&nbsp;<a href="https://www.facebook.com/globaltamilschool/posts/370441997992396">Thursday, July 29, 2021</a></blockquote></div>
<div class="col-md-6 fb-post" data-href="https://www.facebook.com/globaltamilschool/posts/356581559378440" data-width="auto" data-show-text="true"><blockquote cite="https://www.facebook.com/globaltamilschool/posts/356581559378440" class="fb-xfbml-parse-ignore"><p>Dear all, ILACBharathi Tamil school , Amildam Tamil School , Semmozhi tamil school, Global tamil school and Liverpool...</p>Posted by <a href="https://www.facebook.com/globaltamilschool/">Global Tamil School</a> on&nbsp;<a href="https://www.facebook.com/globaltamilschool/posts/356581559378440">Thursday, July 8, 2021</a></blockquote></div>

</div>


</div>





</div>
<div class="clearfix"></div>
</div>
<!--bg note-->
<div class="clearfix"></div>

<?php include "footer.php";?>
<?php include "js.php";?>

</body>
</html>